<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260422100755 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categorie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, type VARCHAR(10) NOT NULL, couleur VARCHAR(7) DEFAULT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE transaction ADD categorie_id INT NOT NULL');
        $this->addSql('ALTER TABLE transaction DROP categorie');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_723705D1BCF5E72D ON transaction (categorie_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE categorie');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1BCF5E72D');
        $this->addSql('DROP INDEX IDX_723705D1BCF5E72D');
        $this->addSql('ALTER TABLE transaction ADD categorie VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE transaction DROP categorie_id');
    }
}
