<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260422095127 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, type VARCHAR(10) NOT NULL, categorie VARCHAR(50) NOT NULL, montant NUMERIC(10, 2) NOT NULL, mode_paiement VARCHAR(30) NOT NULL, description TEXT DEFAULT NULL, piece_jointe VARCHAR(255) DEFAULT NULL, exercice INT NOT NULL, saisir_par_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_723705D1B134FFCC ON transaction (saisir_par_id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1B134FFCC FOREIGN KEY (saisir_par_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1B134FFCC');
        $this->addSql('DROP TABLE transaction');
    }
}
