<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260422124133 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE action_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(20) NOT NULL, module VARCHAR(50) NOT NULL, entite_id INT DEFAULT NULL, details JSON DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B2C5F685FB88E14F ON action_log (utilisateur_id)');
        $this->addSql('ALTER TABLE action_log ADD CONSTRAINT FK_B2C5F685FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE action_log DROP CONSTRAINT FK_B2C5F685FB88E14F');
        $this->addSql('DROP TABLE action_log');
    }
}
